name: Flask-Redis-Test
on:
  push:
    branches: [main]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true



jobs:
  deploy:
#    environment:
#       name: github-pages
#       url: ..........
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      #Download and setup Docker   
      - name: Install Docker on ubuntu
        run: |
         curl -fsSL https://get.docker.com -o get-docker.sh
         sudo sh get-docker.sh
        continue-on-error: false

      # Install Docker Compose
      - name: Check Docker Compose Version
        run: |
         docker compose --version
        continue-on-error: false

        # Build Docker Images
      - name: Prepare Build Docker Images
        run: |
         mkdir -p build
         docker compose -f compose.yaml build

      # Run Docker images 
      - name: Run Docker Compose
        run: |
         docker compose up -d

      # # Deploy to GH-Pages
      # - name: Deploy on github pages
      #   uses: actions/configure-pages@v4
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     branch: gh-pages
      #     folder: build