name: Flask-Redis-Test
on:
  push:
    branches: [main]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true



jobs:
  deploy:
    environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Check if docker exists
      - name: Check if docker exists
        run: |
           echo "Docker version"
           docker version
           echo ""
           echo "_______________________________"
           echo ""
           echo "Docker Compose Version "
           docker compose version
        continue-on-error: false

        # Build Docker Images
      - name: Prepare Build Docker Images
        run: |
         mkdir -p build
         docker compose -f compose.yaml build

      # Run Docker images 
      - name: Run Docker Compose
        run: |
         docker compose up -d

      # # Deploy to GH-Pages
      # - name: Deploy on github pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.0
      # # - name: Upload artifact
      # #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     branch: gh-pages
      #     folder: build